blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/igordanchenko/yet-another-react-lightbox/discussions/categories/q-a
    about: Ask usage questions in the Q&A category
  - name: Idea
    url: https://github.com/igordanchenko/yet-another-react-lightbox/discussions/categories/ideas
    about: Share suggestions or ideas in the Ideas category
  - name: General discussion
    url: https://github.com/igordanchenko/yet-another-react-lightbox/discussions/categories/general
    about: Start a General discussion for anything else
