name: Preview

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  preview:
    name: Publish preview package
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Size
        run: npm run size

      - name: Audit signatures
        run: npm audit signatures

      - name: Record bundle size
        uses: igordanchenko/actions/bundle-size@6007abe989a1243da59096371e23ce02e4566f76 # v1.3.3

      - name: Prune package.json
        uses: igordanchenko/actions/prune-package-json@6007abe989a1243da59096371e23ce02e4566f76 # v1.3.3

      - name: Publish preview
        run: npx pkg-pr-new publish --no-template
