name: Preview

on:
  pull_request:
    branches: [main, next]
  push:
    branches:
      - "feat/**"
      - "preview/**"

jobs:
  preview:
    name: Publish preview package
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions: {}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Publish preview
        run: npx pkg-pr-new publish --no-template
